### ISSUE TITLE
C++11 Initializer Lists marked with error style

### ISSUE THREAD

**Issue by unphased** [octol/vim-cpp-enhanced-highlight#10] opened 2015-05-16 18:56 UTC
![syntax-highlight-fail](https://cloud.githubusercontent.com/assets/1542910/7667586/9d343b44-fbdb-11e4-9b12-ecaba00ff820.PNG)

**Comment by unphased** [comment] 2015-05-16 19:05
The solution is inside of this. 

https://github.com/vim-scripts/Cpp11-Syntax-Support

It should be pretty easy to merge the syntax between these two plugins.

**Comment by unphased** [comment] 2015-05-16 19:06
Opening because there is nothing out of box that gives as much color as cpp-enhanced-highlight and which supports e.g. c++11 initializer list shenanigans.

**Comment by octol** [comment] 2015-05-17 20:32
I'm not able to reproduce the above results on my side. Is your cpp.vim up to date?

**Comment by unphased** [comment] 2015-05-18 00:12
I was in a neovim that I had built very recently. How does the vanilla cpp.vim get updated anyway? Is there a process for that? Or does one need a new build of vim.

**Comment by rr-** [comment] 2015-08-08 07:10
This doesn't work for me as well on fresh `vim-cpp-enhanced-highlight` install.

**Comment by beatmax** [comment] 2015-08-10 09:09
Something like "unordered_set<double>({4,3})" works fine for me, but I still have this case where the curly brackets are red (my Key class has a constructor that takes an initializer_list):

std::map<Key, int> map;
map[Key{"hi", "there"}] = 2;

**Comment by rr-** [comment] 2015-08-10 09:28
I forgot to mention this, but my use case is the same as @beatmax's.

**Comment by octol** [comment] 2015-08-17 08:04
Sorry, that `std::map` example works fine here. I'm using vim in Debian (testing), where my cpp.vim file seems to be last updated 2015-03-01. Upstream for the cpp.vim bundled with Debain is https://github.com/vim-jp/vim-cpp

**Comment by rr-** [comment] 2015-08-17 08:46
It has the same issue, though... https://github.com/vim-jp/vim-cpp/issues/16

**Comment by octol** [comment] 2015-08-17 18:59
@rr-, interesting. I wonder why I don't see it.

**Comment by octol** [comment] 2015-09-19 20:07
Well turns out the reason I've not been able to reproduce it is that I set `let c_no_curly_error=1` in my `.vimrc`. I'm thinking this is more a problem with the core `cpp.vim`.

**Comment by octol** [comment] 2016-10-19 21:19
Since there is a workaround, I'm closing this for now.

**Closed by octol** 2016-10-19 21:19 UTC
